---
- name: Setup for th Ansible Enviroment
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Add "/etc/hosts"
    blockinfile:
      dest=/etc/hosts
      content="
        192.168.56.10 server\n
        192.168.56.11 node01\n
        192.168.56.12 node02\n
        192.168.56.13 node03\n
        192.168.56.14 node04\n
        192.168.56.15 node05"
  - name: Add "etc/ansible/hosts"
    blockinfile:
      dest=/etc/ansible/hosts
      content="
        [CentOS]\n
        node01\n
        node02\n
        [Ubuntu]\n
        node03\n
        node04\n
        [Win]\n
        node05 ansible_connection=winrm ansible_ssh_user=vagrant ansible_ssh_port=5985" 
  - name: Install python2-winrm  # 버전 호환성
    yum:
      name: python2-winrm
      state: present    
  # - name: Install pip
  #   yum:
  #     name: python-pip
  #     state: present
  # - name: Install pywinrm
  #   pip:
  #     name: pywinrm
  #     state: present
  - name: Install sshpass
    yum:
      name: sshpass
      state: present

  - name: Install vim-enhanced
    yum:
      name: vim-enhanced
      state: present
  - name: Install git
    yum:
      name: git
      state: present
  - name: Download pathogen.vim
    shell: "curl -fLo /home/vagrant/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim"
  - name: Git clone vim-ansible-yaml
    git:
      repo: "https://github.com/chase/vim-ansible-yaml.git"
      dest: /home/vagrant/.vim/bundle/vim-ansible-yaml
  - name: Configure vimrc
    lineinfile:
      dest: /home/vagrant/.vimrc
      line: "{{ item }}"
    with_items:
      - "set number"
      - "execute pathogen#infect()"
      - "syntax on"
  - name: Configure Bashrc
    lineinfile:
      dest: /home/vagrant/.bashrc
      line: "{{ item }}"
    with_items:
      - "alias vi='vim'"
      - "alias ans='ansible'"
      - "alias anp='ansible-playbook'"